networks:
  app_net:
    driver: bridge

services:
  django-app:
    build: backend
    #container_name: ${DJANGO_CONTAINER_NAME:-django-app} # Disabled: Dokploy
    restart: always
    env_file:
      - path: .env
    ports:
      - ${DJANGO_PORT:-8888}:8000 # Map the Django port
    volumes:
      - db_data:/app/data/db          # Persist SQLite database file
      - media_data:/app/data/media    # Persist uploaded media files
      - static_data:/app/data/static  # Persist collected static files
    networks:
      - app_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:  # Healthcheck to ensure the service is up
      test: ["CMD", "curl", "-f", "http://django-app:8000"]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    image: nginx:latest
    #container_name: ${NGINX_CONTAINER_NAME:-nginx-test} # Disabled: Dokploy
    restart: always
    env_file:
      - path: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro          # Config file
      - angular:/usr/share/nginx  # Angular build
      - media_data:/app/data/media                              # Media files directory
      - static_data:/app/data/static                            # Static files directory
    networks:
      - app_net
    ports:
      - ${NGINX_PORT:-8001}:80 # Map the Nginx port
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - django-app
      - angular-app

  angular-app:
    build: frontend
    volumes:
      - angular:/app/dist  # Persist build output
    networks:
      - app_net


volumes:
  db_data:
  media_data:
  static_data:
  angular: